<script type="text/javascript" src="/js/jquery-1.8.2.min.js" ></script>
<style>
<!--
@IMPORT url("/css/general.css");
-->
</style>

<h1>Welcome <?=$this->loginuser['name']?> to the Hall</h1>
<div>
	<ul>
		<li>Book Name</li>
		<li class="narrow" class="narrow">Price</li>
		<li>Publisher</li>
		<li>Date Purchase</li>
	</ul>
	<?php foreach ($this->books as $book) {?>
	<ul>
		<li><?=$book['name']?></li>
		<li class="narrow"><?=$book['price']?></li>
		<li><?=$book['publishHouse']?></li>
		<li><a href="/shopping/addproduct?bookid=<?=$book['id']?>">Buy</a></li>
	</ul>
	<?php } ?>
</div>
<div id="mycart">
	<a href="#" id="checkcart">Check Cart</a>
</div>
<script type="text/javascript">
<!--
	$("#checkcart").click(function(){
		window.location.href="/shopping/showcart";
	});
//-->
</script>
